### ISSUE TITLE
can you supply a demo for mysql

### ISSUE THREAD

**Issue by suluoniu** [thomaxxl/safrs#12]
I modfied the skype_rest for mysql, but it does't work, can you supply a  demo for mysql

**Comment by thomaxxl** [comment]
I'll prepare an example in a couple of days.
Maybe you can provide me an example schema you'd like to see exposed?

The main issue with exposing existing dbs are composite keys: safrs expects a single pk, preferably named "id" . I'll heave to check how to make this a bit more flexible.

**Comment by suluoniu** [comment]
I think your model (users,books) is ok. Just hope "id" is int,and auto_increment.

**Comment by thomaxxl** [comment]
Hi,

I created a demo for using auto_increment ids with mysql: https://github.com/thomaxxl/safrs/blob/master/examples/demo_relationship_mysql.py 

I will create the automap example tomorrow

**Comment by thomaxxl** [comment]
I didn't manage to get the automap working yet :/
I removed the assert that was causing errors but relationships don't get serialized. I think I should fix the mro but I didn't find the time unfortunately. I will look at this again later.

**Comment by suluoniu** [comment]
thank you very much! looking forword to your solution for it. This project is very amazing to me ,a beginner of python and flask

**Comment by thomaxxl** [comment]
I'll keep this issue open until it's resolved.
I think the actual codechanges will be quite small but it requires some advanced understanding of python internals and this project to get everything working as expected. 
Unfortunately the time available for me to work on this is fairly limited atm :/

Please feel free to open another case if you have other questions or bug reports.

**Comment by thomaxxl** [comment]
Also, if you want to use with an exisiting db, maybe you can start from https://github.com/agronholm/sqlacodegen

**Comment by thomaxxl** [comment]
I exposed the sample mysql databases "employees" and "sakila" as a jsonapi service
( https://github.com/datacharmer/test_db )

using a [modified sqla_codegen](https://github.com/thomaxxl/safrs/tree/master/sqlacodegen) and  [expose_employees.py](https://github.com/thomaxxl/safrs/blob/master/examples/expose_employees.py) and [expose_sakila.py](https://github.com/thomaxxl/safrs/blob/master/examples/expose_sakila.py).

I'll write up an explanation later.

**Comment by thomaxxl** [comment]
I added a short explanation to the readme in the examples:
https://github.com/thomaxxl/safrs/tree/master/examples#expose-existing-databases
