### ISSUE TITLE
Using With Flask-Jwt-Extended

### ISSUE THREAD

**Issue by ozanonurtek** [thomaxxl/safrs#14]
Hello,

I find your framework very helpful and open to development. I wonder, if it works with flask-jwt-extended or not. Since aim of your framework is creating endpoints using sqla models and flask-jwt-extended works with decorators, do you think that entegration of these two framework is possible or not? If so, I'll give a try coz I really need a handy framework like safrs.

Thanks for your effort.

**Comment by thomaxxl** [comment]
Hi,

Glad you find my project useful :)
I implemented access control with flask_login but I didn't add it to github and I don't have access to the code at the moment.

I'll have to look into flask-jwt-extended to see how it can be integrated, I'm sure it's possible but I think it will be pretty difficult to implement unless you're familiar with flask routing internals.

I'll check it out next week. If you want to dig into it yourself, I'll be glad to answer any questions though.

**Comment by ozanonurtek** [comment]
If flask_login can be implemented, I believe that we can also implement JWT based authentication too. I'll also dive into this next week, thanks for your support :)

**Comment by thomaxxl** [comment]
So, I have authentication with flask_login working integrated in a prod environment.
I tried to copy bits and pieces to a demo but it's not working yet. I'll redo it.
This is what I have now: 
https://github.com/thomaxxl/safrs/blob/master/examples/demo_full.py

It's too complicated atm. The idea is to check authorization in app.before_request using api.routes . 
I'll make a simpler demo for flask_login later, then one for flask-jwt-extended .

**Comment by thomaxxl** [comment]
I created a simple authentication example : A token is generated if a valid user/pass is entered for /api/token.

https://github.com/thomaxxl/safrs/blob/master/examples/demo_auth.py

Let me know if something isn't clear, I'll try to integrate this with jwt later.

**Comment by thomaxxl** [comment]
I added an example with JWT:

https://github.com/thomaxxl/safrs/blob/master/examples/demo_jwt.py

This requires the latest commit from the repo: I added the "custom_decorators" class variable to apply custom decorators to the exposed http methods. I then use this to add the jwt_required decorator.

I'll clean it up tomorrow.

**Comment by thomaxxl** [comment]
I updated the example, swagger authorization is added to the swagger ui. 

https://github.com/thomaxxl/safrs/blob/master/examples/authentication/demo_jwt.py
