### ISSUE TITLE
in version 3.0 _s_count function does not apply filters to query

### ISSUE THREAD

**Issue by nlapierre-isp** [thomaxxl/safrs#146]
Just a heads up, it looks like the _s_count function doesnt add filters to the count cls.query.count() call. I fixed this locally in our code by overriding the function with:
            `count = cls.jsonapi_filter().count()`

Simple PR to add this: https://github.com/thomaxxl/safrs/pull/147

**Comment by thomaxxl** [comment]
Thanks,  I will fix this the next days.
