### ISSUE TITLE
Wrong creation of "empty" object on initalization

### ISSUE THREAD

**Issue by dwolff** [thomaxxl/safrs#15]
https://github.com/thomaxxl/safrs/blob/0ae2615649fa7b4207b62a0f2af1cfec6ac94709/safrs/jsonapi.py#L99

I've found out that this  "try" block was causing a small problem: creating an empty object (just with an id).

After commenting it, the problem was gone. Is it really necessary?

Also:
- the examples requires a logging import that is not explicit on the examples files. (look demo.py)
- why do the primary keys have to be a uuid (string)? Can't it be an integer (what is very common on pre-existing databases)

**Comment by thomaxxl** [comment]
Regarding the primary keys, you can use a different "id_type" for other types of primary keys. I should document this better though. I created a demo fro mysql auto-increment ids: https://github.com/thomaxxl/safrs/blob/master/examples/demo_relationship_mysql.py
I changed how this part of the code works recently however, I hope everything still works as expected.

Also, I think the demo and implementation is quite complicated so I'll have to figure out how to simplify this.

I'll replace the logging from the demos by print statements.

Thanks for your input, much appreciated. Please let me know if you have other questions, ideas or suggestions.

**Comment by thomaxxl** [comment]
I changed the support for Integer PKs, this should now work as expected without the id_type crap, e.g.

```
class User(SAFRSBase, db.Model):
    __tablename__ = 'users'
    id = Column(Integer, primary_key=True)
    name = Column(String, default = '')
```

**Comment by thomaxxl** [comment]
I changed the logging a bit but I still have to change the examples

I removed the tmp_obj creation in the latest release, safrs==1.0.22 

Integer primary keys should also work without extra work
