### ISSUE TITLE
Missing examples/template folder

### ISSUE THREAD

**Issue by jordiyeh** [thomaxxl/safrs#22]
Hi Thomas - Thanks for the project. Would it be possible to add the templates folder to GitHub? I was running the demo_full.py, but was getting an error with missing my_master.html file when trying to access the admin UI

Getting a copy of https://github.com/flask-admin/flask-admin/blob/master/examples/auth/templates/my_master.html seem to work.

Thanks,

**Comment by thomaxxl** [comment]
hi, iirc flask-admin doesn't need the templates if nothing is modified, it will use the default templates.
Which flask-admin version do you use? Can you try demo_pythonanywhere_com.py ?

I'll check tomorrow.

**Comment by thomaxxl** [comment]
I removed the `base_template` argument from the example so it doesn't require the templates directory. The flask-admin should work now. Thanks for letting me know about this bug!

**Comment by thomaxxl** [comment]
Oh damn, other flask-admin templates are needed too to get this working properly/securely but I can't upload them to github right now. I'll fix it later.
