### ISSUE TITLE
lazy loading ?

### ISSUE THREAD

**Issue by euri10** [thomaxxl/safrs#24]
I may be mistaken but I didn't see a way to lazy load the Api object so that it's easily usable with the app factory pattern, is this something achievable ?

**Comment by thomaxxl** [comment]
I wasn't aware of the app factory pattern until now :/ I'll check it out .
Can you provide some pseudo code? Then I'll try to implement it .

**Comment by euri10** [comment]
In essence the init_app method exists so that the object can be instantiated without requiring an app object.

I would badly rephrased what is very well explained in the Flask doc here:
http://flask.pocoo.org/docs/1.0/patterns/appfactories/

You can see the interest given the app factory pattern to lazy load an extension here:
http://flask.pocoo.org/docs/1.0/patterns/appfactories/#factories-extensions

and finally I think the best example is here for extensions:
http://flask.pocoo.org/docs/1.0/extensiondev/#initializing-extensions

hope this helps

**Comment by thomaxxl** [comment]
You can use init_app in v1.1.0 if that's what is meant (db is initialized with `db=SQLAlchemy()` in __init__.py) .

I made an example with `create_app`, but it requires the latest commits (where I added `SAFRSAPI` )
https://github.com/thomaxxl/safrs/blob/master/examples/mini_app.py, can you tell me if this works for you?

**Comment by euri10** [comment]
looks like it's perfect
merci beaucoup

**Comment by thomaxxl** [comment]
ok, feel free to open another issue if you have more questions.
