### ISSUE TITLE
Port not included in swagger interface

### ISSUE THREAD

**Issue by patvdleer** [thomaxxl/safrs#27]
I'm not sure wetter or not I'm forgetting something or this is an actual bug... If I don't add the port to the host it "forgets" to add it in the URL.

host = "localhost"
port = 5000

`api = SAFRSAPI(app, host=host, port=port, prefix=api_prefix)`

![image](https://user-images.githubusercontent.com/1138136/54194379-6d4fd680-44bc-11e9-86b9-833365c3c198.png)

`api = SAFRSAPI(app, host=host+":"+str(port), port=port, prefix=api_prefix)`

![image](https://user-images.githubusercontent.com/1138136/54194339-4ee9db00-44bc-11e9-8893-2c5bc3475f22.png)

**Comment by thomaxxl** [comment]
You are right, this is badly implemented and I'll change it.

in the meantime you can use 
```python
api = SAFRSAPI(app, host='{}:{}'.format(HOST,PORT), prefix=API_PREFIX)
```
( cfr. https://github.com/thomaxxl/safrs/blob/master/examples/demo_relationship.py )

**Comment by patvdleer** [comment]
Thanks, and for another thanks for the work and quick response!
