### ISSUE TITLE
disable `POST /model/{modelId}/`

### ISSUE THREAD

**Issue by patvdleer** [thomaxxl/safrs#29]
Is there an easy way to disable the post with the model ID? i.e. `POST /model/{modelId}/` since the ID is autoincrement I don't want to let the api client be able to post/create to a certain ID/number.

P.s. sorry for the amount of issues.

**Comment by thomaxxl** [comment]
Hi Patrick, 

IIRC the IDs are generated server-side so it shouldn't be possible to create an item with a user-defined ID so the POSTs to /model/{modelId}/ should probably be deleted altogether.
Does a POST to /model/{modelId}/ work for you?

no worries about the amount of issues, I want this thing to be perfect :), I'll be on holiday next week however :| .

**Comment by thomaxxl** [comment]
In 10aee62b8f08f96142995b764b32a712e66fdb6e I removed the swagger and changed the jsonapi POST request processing a bit. I try to follow the spec, eg. https://jsonapi.org/format/#crud-creating-client-ids . 

Also, you should be careful when implementing fine-grained access control: We're pretty much reading and writing to the database directly, this may be a bit dangerous. For example by requesting related resources through the "include" request parameter it may be possible to retrieve information that you would like to hide. Similarly, POSTing to a relationship may cause related database objects to be updated.

**Comment by patvdleer** [comment]
is there an easy way to hide certain attributes? for example the password hash of a user?

**Comment by thomaxxl** [comment]
You can overwrite the _s_to_dict method. I should update the readme, it is still called to_dict there.

**Comment by thomaxxl** [comment]
fixed in v2.1.0
