### ISSUE TITLE
returning relations

### ISSUE THREAD

**Issue by patvdleer** [thomaxxl/safrs#33]
Is it possible to return, for example, the authors of the book, out of the box?

Lets say I query the books and I would like to display the authors as well, currently this leaves me with 2 options, 1 query all authors or 2 query them individually.

```python
class Book(Model):
    """Book"""
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))
    sortable_title = db.Column(db.String(255))
    language = db.Column(db.String(3), comment="ISO-639-2")
    editions = db.relationship("BookEdition", uselist=False, back_populates="book")
    authors = db.relationship(
        "Author",
        secondary=author_book_table,
        back_populates="books",
        lazy='dynamic'
    )
```

```
"relationships": {
        "authors": {
          "data": [
            {
              "id": 1,
              "type": "author"
            },
            {
              "id": 2,
              "type": "author"
            },
            {
              "id": 3,
              "type": "author"
            }
          ],
          "links": {
            "self": "http://localhost:5000/book/1/authors"
          },
```

**Comment by thomaxxl** [comment]
Hello Patrick,

I don't understand exactly what info you want to retrieve. Do you think your query is possible within the json:api spec ? Can you elaborate?

The authors should be included if you add the `Book?include=author` url query parameter.
If you know the ids of the authors, you can use the `filter[id]` query parameter, eg. `Author?filter[id]=1,2,3` .

**Comment by patvdleer** [comment]
Thanks this indeed solves it, I was looking for the data in the wrong place in the response, i.e. time for weekend.
