### ISSUE TITLE
swagger.json not found

### ISSUE THREAD

**Issue by d-paulus** [thomaxxl/safrs#34]
Hi,

great project. Letting the models get created from an existing database and accessing them through REST calls work, but the Swagger doc is not being created? swagger.json can't be found.

Best regards,
David

**Comment by thomaxxl** [comment]
Hi,

The code changed somewhat since I created expose_existing.py and the readme.
If you managed to create the models you should be abe to use them like in the examples (eg https://github.com/thomaxxl/safrs/blob/master/examples/demo_relationship.py ).

I'll try to make the script up to date asap.

**Comment by thomaxxl** [comment]
Hi,

I updated [expose_existing.py] (https://github.com/thomaxxl/safrs/blob/master/expose_existing/expose_existing.py)  so it works with safrs v2.x ( c9485480887f2195b54b3cd92c9b1b30247b11f4 )

Thanks for letting me know about this issue.

**Comment by d-paulus** [comment]
Thanks Thomas, I will check it out. I had made these few changes (https://github.com/HumTechLab/AIF-API/blob/master/htl-aif-api.py) to just have something running quickly. Will adapt it to your code.
