### ISSUE TITLE
Related instaces on init

### ISSUE THREAD

**Issue by wicol** [thomaxxl/safrs#35]
I'm trying out SAFRS by re-implementing an existing API based on flask-sqlalchemy. One issue I'm facing trying to re-use the migration files is passing in related instances on model init:
```
# Doesn't work but can be worked around using parent_id=some_obj.id
obj = MyModel(parent=some_obj)
# Doesn't work and the workaround is a bit messy
obj = MyModel(children=[c1, c2])
# In my migration I'm actually doing this which works natively with sqlalchemy
obj = MyModel(children=[Child(), Child()])
```
This `continue` looks to be the culprit?:
https://github.com/thomaxxl/safrs/blob/master/safrs/db.py#L144

What's the story there? Would it be possible to just un-comment that stuff (or what about calling super to let sqlalchemy deal with this natively..?)

Edit:
FYI my workaround for now is using this ABC:
```
class BaseModel(SAFRSBase, db.Model):
    __abstract__ = True
    db_commit = False

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        db.Model.__init__(self, *args, **kwargs)
```

**Comment by thomaxxl** [comment]
Hi,

I don't remember why i commented that :/
Uncommenting that part may work. I'll check it out later and let you know.

**Comment by thomaxxl** [comment]
I think I removed that part because it may cause errors when invoked from the web context.
I've  commited a solution (b731f0a26f54d29ace2eeb60ec5940aa0f19583c) but I'll have to test this a bit more.

**Comment by thomaxxl** [comment]
v2.2.1 should fix this now

**Comment by wicol** [comment]
Sorry to dig this up again, but I ran into the same problem again when trying to create an instance with related objects in an RPC (GET) endpoint. `__init__` doesn't take care of it since it's in a request context, and neither does `SAFRSRestAPI.post` of course.
Maybe the check should be more specific - somehow just covering if the instance has been handled by a generic SAFRSRestAPI-endpoint  or not..?

**Comment by thomaxxl** [comment]
I see,

Can you remove the ```not request and``` from 

```python
            if not request and rel_attr:
```
in 
https://github.com/thomaxxl/safrs/blob/master/safrs/db.py#L130  

and see if that works for you? ie.

```python
            if rel_attr:
                # This shouldn't in the work in the web context
                # because the relationships should already have been removed by SAFRSRestAPI.post
                db_args[rel_name] = rel_attr

```

**Comment by thomaxxl** [comment]
I suppose you instantiate the objects from a jsonapi_rpc method and not using a POST/PATCH ?

I didn't think of this use case, and the check for request context is somewhat redundant anyway (because the related items should have already been removed)

**Comment by wicol** [comment]
Exactly. The object is being created/populated by some other logic.
I tried removing the check for request and it works 👍

**Comment by thomaxxl** [comment]
Ok, I will remove it in the following release.
