### ISSUE TITLE
simple flask endpoint

### ISSUE THREAD

**Issue by rmlopes** [thomaxxl/safrs#38]
How can I use swagger_doc to document a simple flask app? What I am trying:

```python
@jsonapi_rpc(http_methods=["GET"])
@app.route("/hello/<name>", methods=["GET"])
def hello(name):
	"""
        pageable: True
        description : Hello world
        args:
            name: greeters name
    """
	return make_response("Hello World from %s!"%name, 201)

api = SAFRSAPI(app, host="0.0.0.0", port=5000, prefix="/swagger")
```

The resulting json has the metadata, but no paths.

**Comment by thomaxxl** [comment]
Hi,

This only works for object methods atm, you should create a `SAFRSBase` object containing your `hello` method.

**Comment by rmlopes** [comment]
Thanks @thomaxxl. Then I will not be able to use it as is without a model, or am I missing something?

```python
class Hello(SAFRSBase):
	@classmethod
	@jsonapi_rpc(http_methods=["GET"])
	@app.route("/hello/<name>", methods=["GET"])
	def hello(name):
		"""
	        pageable: True
	        description : Hello world
	        args:
	            name: greeters name
	    """
		return make_response("Hello World from %s!"%name, 201)

api = SAFRSAPI(app, host="0.0.0.0", port=5000, prefix="/swagger")
```

**Comment by thomaxxl** [comment]
Safrs is created for CRUD operations. jsonapi_rpc is a bit of a hack on top of this.
I think there are other frameworks that will better suit your needs if you need rpc.

I may eventually extend the rpc interface but not anytime soon.

**Comment by rmlopes** [comment]
Ok, thanks for the input. I'll close the issue.
