### ISSUE TITLE
SAFRSRestRelationshipAPI returns all objects in db of the related type

### ISSUE THREAD

**Issue by wicol** [thomaxxl/safrs#41]
Hi, I just noticed `/<obj_type>/<obj_id>/<child_obj_type>` returns all instances of `child_obj_type` in my database. It seems a correct subset of related objects are present on line 853 here, but then an unfiltered query of the related object is fetched from `jsonapi_filter`:

https://github.com/thomaxxl/safrs/blob/master/safrs/jsonapi.py#L853-L855

I'm guessing the intention was to have filtering support for the related objects. If that's the case then perhaps `jsonapi_filter` and `SAFRSBase._s_filter` could take an optional argument for a prepared query that is to be filtered?

**Comment by thomaxxl** [comment]
well, this is a pretty unfortunate screwup.
I'll have to think how to fix this: problem is that the relationship can be either an instance of 
- AppenderBaseQuery (in the case the relation has been configured with lazy="dynamic". This would be ok
- InstrumentedList, in which case I can't perform any more queries on it

anyway, following may fix it temporarily

```python
            data = [item for item in relation if isinstance(item, SAFRSBase)]
            meta = {"direction": "TOMANY"}
            instances = jsonapi_filter(self.child_class)
            instances = jsonapi_sort(instances, self.child_class)
            #links, data, count = paginate(instances, self.child_class)
            links = {}
            count = len(data)
```

but there are obv other issues: no filtering and sorting and the lack of pagination means it will work badly for large relations

I'll have to investigate this a bit further

**Comment by wicol** [comment]
If it's an InstrumentedList perhaps one could construct a base query manually: `self.child_class.query.filter(self.child_class.id.in_([item.id for item in relation]))` or something (but with dynamic primary key name I guess).

Or maybe the lazyness can be overridden temporarily in this case..? Not sure how though.

**Comment by thomaxxl** [comment]
I've commited a fix.
I should make the sort/filter/paginate more consistent eventually, but I think this will work for now.

**Comment by wicol** [comment]
Too bad filtering was omitted, but at least it works now 👍 
Btw, opting for other loading techniques than dynamic at declaration time is basically a choice made not to enable filtering or sorting, isn't it? Considering that, it might be easier to allow these operations only when the relationship is of the query type.

**Comment by thomaxxl** [comment]
I'll implement filtering and sorting too, but these have to reimplemented on list objects instead of query objects :/
