### ISSUE TITLE
How to add sample value (column default= is not working)

### ISSUE THREAD

**Issue by zsinnema** [thomaxxl/safrs#51]
When I try to add sample value through the default value of a field this sample value isn't shown in the example block POST body. See screen print.
![no_sample_value_in_experiment_ name](https://user-images.githubusercontent.com/124044/73033238-60f01600-3e0f-11ea-955d-85d30a656e98.png)

My model Experiment looks like this:
`
class Experiment(SAFRSBase, db.Model):
    """
        description: Experiment
    """

    __tablename__ = "experiments"
    exclude_rels = ["datafile"]
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, default="Experiment 1")
    description = db.Column(db.String, default="")
`

May be here https://github.com/thomaxxl/safrs/blob/c982bd30de5cde4bca493279aca619fc85a24c88/safrs/base.py#L658 should be an `else:` ?

or it would even be nicer to have an extra Column attribute for example "sample_value"

**Comment by thomaxxl** [comment]
This was a bug, thanks for letting me know.
Can you test with the latest commit?

**Comment by zsinnema** [comment]
thanks lgtm!
do you have any idea when you will push it to pypi?

**Comment by thomaxxl** [comment]
It's on pypi now: v2.6.2

**Comment by zsinnema** [comment]
thanks
