### ISSUE TITLE
Can't use safrs with poetry

### ISSUE THREAD

**Issue by dwolff** [thomaxxl/safrs#52]
For some reason, poetry does not sees the correct dependencies of the safrs library.
"An error occurred when reading setup.py or setup.cfg: 'Attribute' object has no attribute 'id'" -> this message is shown when I do a "poetry install", having "safrs" as a dependency.

Apparently, poetry can't see what libraries safrs depends on.

**Comment by thomaxxl** [comment]
Hi,

Thanks for reporting this problem, I'll look into it this week.

**Comment by thomaxxl** [comment]
Hi, can you provide some more detail about what's not working for you please?

I'm not familiar with poetry. I installed it and added safrs without much trouble though (except poetry used python2.7 at first).
My toml file looks like this:

```
[tool.poetry]
name = "poetry-safrs"
version = "0.1.0"
description = ""
authors = ["Thomas <thomas.pollet@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
safrs = "^2.6.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```
