### ISSUE TITLE
How to not display relationships in the object

### ISSUE THREAD

**Issue by GabrielGhe** [thomaxxl/safrs#55]
Love the project, it helped bootstrap very quickly!

I'd like to be able to an object and all its relationships in the same object.
Why expose the implementation detail to the API user by defining the relationship?

**Comment by thomaxxl** [comment]
Do you want to hide the relationships from the output?

This is demonstrated here (not yet released though so you'll have to clone the repo)

https://github.com/thomaxxl/safrs/blob/09c4720f4b11ef7cdaa561024b2b8925aca81467/examples/demo_pythonanywhere_com.py#L82-L88
