### ISSUE TITLE
The http_method restriction does not apply to a model's relationships

### ISSUE THREAD

**Issue by GabrielGhe** [thomaxxl/safrs#57]
Restrict methods on a model
```
class Item(...):
    http_methods = ["get"]

    instance = db.relationship("Instance")

class Instance(...):
    http_methods = ["get"]
```

Now only `GET` methods should be displayed for `Item` and `Instance`.
```bash
curl https://myhost.com/api/
```

Only `GET` methods should be displayed Item and Instance, but the API page shows `item/<id>/instance` shows `[POST, GET, PATCH, DELETE]`.

**Comment by thomaxxl** [comment]
Thanks!
Can you check if the commit works for you?

**Comment by GabrielGhe** [comment]
Works. Thank you!
