### ISSUE TITLE
Paging state variables always 0

### ISSUE THREAD

**Issue by DennyWeinberg** [thomaxxl/safrs#6]
The function `safrs.jsonapi.paginate` always returns
```
      "links": {
        "first": 0,
        "last": 0,
        "next": 0,
        "prev": 0
      },
```
(hardcoded)
so we don't know if we have other pages or if we reached the last one.

Is it possible to improve this paging function?

**Comment by thomaxxl** [comment]
Hi

I was actually working on that today. Will be implemented asap.


Op vr 4 mei 2018 23:56 schreef Denny Weinberg <notifications@github.com>:

**Comment by DennyWeinberg** [comment]
Whooooot. Nice :)

**Comment by thomaxxl** [comment]
I commited the pagination

**Comment by thomaxxl** [comment]
There are atill bugs.. will check tomorrow

**Comment by thomaxxl** [comment]
solved
