### ISSUE TITLE
Type coercion does not always work for JSON columns

### ISSUE THREAD

**Issue by polyatail** [thomaxxl/safrs#66]
The JSON type in `sqlalchemy` seems to be hard-coded to return `dict` as its `python_type`:

```python
@property
def python_type(self):
    return dict
```

There are many ways valid JSON can be something other than a `dict`. In safrs 2.8.0, these columns fall through to the base case of being coerced to dictionaries [see here](https://github.com/thomaxxl/safrs/blob/master/safrs/base.py#L373):

```python
        else:
            attr_val = attr.type.python_type(attr_val)

        return attr_val
```

This doesn't work if the column is e.g., `None` or a `list`.

**Possible solutions**
* Skip type coercion on JSON columns
* Special-case JSON columns to use `json.loads` if a string and pass through if `None`, a `list`, or `dict`

**Comment by thomaxxl** [comment]
Hi,

You can use json column types like this:

```python
from safrs.safrs_types import JSONType

class Item(SAFRSBase, db.Model):
    __tablename__ = "items"
    id = db.Column(db.Integer, primary_key=True)
    foo = db.Column(db.String(32))
    json = db.Column(JSONType)

```

However, this isn't well tested.

I will try to support the sqla json type natively, but iirc this kinda depends on the db implementation as well.

**Comment by polyatail** [comment]
Hi Thomas,

Thanks for the tip! I ended up subclassing `db.JSON` and overloading the `python_type`, like this:

```python
class JSONList(db.JSON):
    @property
    def python_type(self):
        return list
```

I noticed that the `JSONType` that ships with safrs works, but only because `NotImplementedError` is explicitly caught in `_s_parse_attr_value()`. What do you think if we skip type coercion on `db.JSON` columns since we don't really know what type of data is in there?
