### ISSUE TITLE
PATCH method on resources returns 201 status code, rather than 200

### ISSUE THREAD

**Issue by Alan-Robinson** [thomaxxl/safrs#68]
The PATCH method on resources returns 201 (Created) if successful, with a body containing the updated resource.

The jsonapi spec (https://jsonapi.org/format/#crud-updating-responses) permits any of 200 (OK), 202 (Accepted) or 204 (No Content) to be returned, so returning 201 (Created) is incorrect.  For the current behaviour of returning the updated resource in the response body, 200 (OK) would be the correct status code.

This only seems to affect resources - the PATCH method on relationships correctly returns 200.

**Comment by thomaxxl** [comment]
Fixed in release 2.9.0
