### ISSUE TITLE
Pagination doesn't support more than 2 pages

### ISSUE THREAD

**Issue by glungley** [thomaxxl/safrs#70]
https://github.com/thomaxxl/safrs/blame/master/safrs/jsonapi_formatting.py#L140

MAX_PAGE_LIMIT limits the size of a page (default 250).
This value is also used to limit the size of the page offset.

Therefore only limit + page offset records can be fetched. Meaning only the first `MAX_PAGE_LIMIT*2` (500) records can be fetched.

**Comment by thomaxxl** [comment]
Thanks for reporting this issue!
I added a MAX_PAGE_OFFSET config parameter (cb7fba73d816b0b14b5676505ccbe4a98c9d4960)
