### ISSUE TITLE
Link to Flask-Admin frontend returns a 404

### ISSUE THREAD

**Issue by jbeard4** [thomaxxl/safrs#76]
Hello,

The link to the Flask-Admin frontend returns a 404 page on the live demo ([here](http://thomaxxl.pythonanywhere.com/admin/person), and when running locally on master branch. 

Thank you for your consideration.
![Screenshot from 2020-09-19 19-39-29](https://user-images.githubusercontent.com/586962/93691190-f97a8b00-faaf-11ea-87aa-c96fc7eee783.png)

**Comment by jbeard4** [comment]
On my local, I was able to resolve this by running `pip install flask_admin`

Is there a reason why flask_admin is not listed as a dependency in requirements.txt? Is it meant to be an "extra/optional dependency"?  If so, [PEP-0508](https://www.python.org/dev/peps/pep-0508/#extras) provides a nice syntax for expressing this in your requirements.txt, so that the user needs to opt into installing it. I would be happy to contribute this as a feature if that would be helpful.

Thanks.

**Comment by thomaxxl** [comment]
Hi,

Flask-admin is optional indeed, I wasn't aware of PEP-0508, and I'd be happy to accept a PR.

**Comment by jbeard4** [comment]
Thanks for your reply. I will follow up with you shortly on this.

**Comment by thomaxxl** [comment]
I've added flask_admin as an extra requirement (i.e. safrs[admin]). I'll update the documentation too.

**Comment by jbeard4** [comment]
Thank you!
