### ISSUE TITLE
requirements.txt too restrictive

### ISSUE THREAD

**Issue by frip** [thomaxxl/safrs#81]
I am using [pip-tools](https://github.com/jazzband/pip-tools) to pin the requirements in my project which uses safrs next to many other dependencies. Some of my dependencies have upper and some lower version bounds, so my requirements are somewhat constrained.

pip-tools' `pip-compile` reads the requirements.txt of safrs and takes it literally, so in particular I get `Flask-SQLAlchemy==2.3.2` while I require `Flask-SQLAlchemy>=2.4` elsewhere. 

As far as I understand, a requirements.txt with pinned versions would be appropriate for an application, while it would be good if safrs worked as a package, in which case it shouldn't be so restrictive. Maybe it would be sufficient to define minimal dependencies and version-bounds in setup.py (-> install_requires) and leave out the requirments.txt alltogether?

Unfortunately I have lost my references to the sane "do"s and "don't"s of Python requirements, and the subject is neither simple, nor historically consistent, nor free of emotional controversies. In any case it would be great if you could modify your requirement-specification to match the high quality of safrs as a whole!

**Comment by thomaxxl** [comment]
I'll change the Flask-SQLAlchemy requirement to `>=` in the next release.
