### ISSUE TITLE
Duplicate definitions generated

### ISSUE THREAD

**Issue by Veabers** [thomaxxl/safrs#82]
Multiple calls to SchemaClassFactory in swagger_doc.py for the same class generates duplicate definitions in the swagger.json.

The duplicates are named differently such as User_post_inst1 and User_post_inst, but in reality reference the same class definition.

Running the example:
python3 examples/demo_relationship.py "your-interface-ip"

**Comment by thomaxxl** [comment]
Hi,

I added the `idx` because it may happen the given name already exists for another object.
I think this code resolves this issue:

```python
def SchemaClassFactory(name, properties):
    """
    Generate a Schema class, used to describe swagger schemas
    :param name: schema class name
    :param properties: class attributes
    :return: class
    """

    # generate a unique name to be used as a reference
    idx = Schema._reference_count.count(name)
    if idx:
        if Schema._references[name].properties == properties:
            return Schema._references[name]
        name = name + str(idx)
        
    Schema._reference_count.append(name)

    def __init__(self, **kwargs):
        for key, value in kwargs.items():
            # here, the properties variable is the one passed to the
            # ClassFactory call
            if key not in properties:
                raise ValidationError("Argument {} not valid for {}".format(key, self.__class__.__name__))
            setattr(self, key, value)

    new_schema_cls = type(name, (Schema,), {"__init__": __init__, "properties": properties})
    
    Schema._references[name] = new_schema_cls
    return new_schema_cls

```

I'll have to test this for a while though, I don't have enough tests for the swagger generation so I'll have to verify manually.
(I've wanted to rewrite all of the swagger using another library but I never found time or motivation doing this).

**Comment by Veabers** [comment]
I think for this to work the sample passed in will need to be updated to always be consistent.

Specifically lines 870-873 in base.py
`
                        if column.type.python_type == datetime.datetime:
                            arg = str(datetime.datetime.now())
                        elif column.type.python_type == datetime.date:
                            arg = str(datetime.date.today())
`
The now and today need to be something like min
`
                        if column.type.python_type == datetime.datetime:
                            arg = str(datetime.datetime.min)
                        elif column.type.python_type == datetime.date:
                            arg = str(datetime.date.min)
`

**Comment by thomaxxl** [comment]
Thanks for pointing this out, the same problem occurs with dynamically generated sample ids.
If you need this I can release an update with these changes by the end of the week I think. Please let me know if there's something else that's not working for you.

The projects I'm working on don't parse the swagger so I'm not too familiar with the correct way to implement it. I added it as a convenient UI, but it has grown beyond what I initially needed and intended. The library as a whole needs a rewrite but I don't have the time for that atm and as long as there are no functional deficiencies I just keep hacking the existing code.

**Comment by thomaxxl** [comment]
Can you check if this works for you?
There may still be duplicate definitions in the relationship schemas though.

**Comment by thomaxxl** [comment]
v2.10.5
