### ISSUE TITLE
expose_existing starts but no swagger.json found

### ISSUE THREAD

**Issue by jmsy00** [thomaxxl/safrs#84]
Hi,

I was able to get the expose_existing.py script to generate a models.py file from an existing mssql db, but the http://localhost:5000/api shows an error 'Not found api/swagger.json'

what am I doing wrong?

also:
when I step through with a debugger, the static_folder that the swagger_ui blueprint is pointing to is the dist/ folder for flask_swagger_ui

thanks,

**Comment by thomaxxl** [comment]
Hi,

This is a mistake in the script, can you try with the latest commit please?
