### ISSUE TITLE
Run in example demo_relationship.py creating users or books in flask_admin returns Integrity Errors

### ISSUE THREAD

**Issue by agoe** [thomaxxl/safrs#85]
Integrity error. (sqlite3.IntegrityError) NOT NULL constraint failed: Users.id [SQL: INSERT INTO "Users" (name, email) VALUES (?, ?)] [parameters: ('user4711', 'u4711@mail.com')] (Background on this error at: http://sqlalche.me/e/13/gkpj)

Primary Key is missing  in the Insert Syntax.

class User(SAFRSBase, db.Model):
__tablename__ = "Users"
 id = db.Column(db.String, primary_key=True)

**Comment by thomaxxl** [comment]
Hi,

By default, SAFRSBase automatically commits in `__init__`, however since flask-admin commits again, this causes the error.
you can set `SAFRSBase.db_commit = False` to resolve this.

**Comment by agoe** [comment]
Thanks for the quick response.

Unfortunately, I still cannot get the admin part running.

view.py

 def create_model(self, form):
        """
            Create model from form.

            :param form:
                Form instance
        """
        try:
            model = self.build_new_instance()

            form.populate_obj(model)
            self.session.add(model)
            self._on_model_change(form, model, True)
            self.session.commit()

def build_new_instance(self):
    """
        Build new instance of a model. Useful to override the
Flask-Admin behavior
        when the model has a custom __init__ method.
    """
    model = self._manager.new_instance()

The model ( Book) seems to be created without triggering the _init_
constructor to create the uuid

Model (book) in debugger:
id = {NoneType} None
id_type = {type} <class 'safrs.safrs_types.Book_ID'>
jsonapi_id = {str} 'Non

Kind regards,

Achim

**Comment by thomaxxl** [comment]
Hi,

Can you see if this script works for you? https://github.com/thomaxxl/safrs/blob/master/examples/demo_pythonanywhere_com.py 

it's the exact same version deployed on 
http://thomaxxl.pythonanywhere.com/ with flask-admin at http://thomaxxl.pythonanywhere.com/admin/

**Comment by agoe** [comment]
Hi,
did a quick test. Same issue
Integrity error. (sqlite3.IntegrityError) NOT NULL constraint failed:
Books.id [SQL: INSERT INTO "Books" (title, reader_id, author_id,
publisher_id, published) VALUES (?, ?, ?, ?, ?)] [parameters: ('Titlexyz',
1, 2, 1, '01:02:00.000000')] (Background on this error at:
http://sqlalche.me/e/13/gkpj)

I think flask-admin prevents the execution of __init__.
and there is no UUID created

there seems to be also a lot of SQL statements executed by  flask-admin

My models with autoincrement pk run fine.

For example, SQLalcheny does similar stuff:
https://docs.sqlalchemy.org/en/14/orm/constructors.html


Very nice project.

Achim





Achim

**Comment by thomaxxl** [comment]
Ok, I understand now. This behaviour seems to have changed in flask-admin since 1.5.3: https://github.com/flask-admin/flask-admin/issues/1927 .
I'll look into it and keep you updated, thanks for bringing this to my attention.

**Comment by thomaxxl** [comment]
Calling `SAFRSBase.__init__()` from a flask-admin `ModelView` override resolves this

```python
from sqlalchemy.orm.base import instance_state

class TempMV(sqla.ModelView):
    
    def build_new_instance(self):
        model = self._manager.new_instance()
        model.__init__() # <-- Call SAFRSBase.__init__()
        state = instance_state(model)
        self._manager.dispatch.init(state, [], {})
        return model
```
Then use
```python
admin.add_view(TempMV(model, db.session))
```

I'll see if I can fix this in safrs by having a column PK `default=` callable for the uuid types, but I'll have to test for backward compatibility.

**Comment by thomaxxl** [comment]
I can't find a straightforward way to support flask-admin when using `db.String` types used in the examples.
Adding a column default, for ex.
```python
id = db.Column(db.String, primary_key=True, default=lambda _: str(uuid.uuid4()))
```

or overriding the ModelView, like in the previous comment, does resolve this issue.
I could add a bunch of code to safrs to support this use case, but I'd prefer to avoid the bloat.

Maybe you have any suggestions?

**Comment by agoe** [comment]
Hi ,
using a column with default value or a custom view is not a bad option.

I am already overriding ModelView and I tested your code.
I seems to work fine.
Unfortunately the code looks really ugly. But the root cause for this is
thewa flask-admin creates its objects..

So thanks for your help.

I have more problems with your __new_ method

def __new__(cls, *args, **kwargs):
    """
    If an object with given arguments already exists, this object is
instantiated
    """
    # Fetch the PKs from the kwargs so we can lookup the corresponding object
    primary_keys = cls.id_type.get_pks(kwargs.get("id", ""))
    # Lookup the object with the PKs
    instance = None
    try:
        instance = cls._s_query.filter_by(**primary_keys).one_or_none()
    except Exception as exc:  # pragma: no cover
        safrs.log.warning(exc)

    if instance is None:
        instance = super().__new__(cls)

    return instance


The query gets called even when the id param is not filled.
Does this code do more than a session.merge(  ...) would do?
Do you need this to fulfill  jason-api  specification?
Firing the query immediately when an object is created can be undesired.

I might need a copy of the object to capture an old state.
Now I would need similar object creation code  like flask-admin.

At least a switch like db_commit might be helpful.

If i overwrite the __new__ Method

class BaseModel(SAFRSBase):

    def __new__(cls, *args, **kwargs):
        return object.__new__(cls)

I get  File
"C:\Users\ago\PycharmProjects\safrs1\venv\lib\site-packages\safrs\safrs_types.py",
line 144, in get_id_type
    id_type_class = type(cls.__name__ + "_ID", (Super,), {"primary_keys":
primary_keys, "columns": columns, "delimiter": delimiter})
AttributeError: 'StoreModel' object has no attribute '__name__'

As a Java programmer my Python knowledge is not sufficient to deal with
this error.

**Comment by thomaxxl** [comment]
Hi,

This error is caused because `SAFRSBase.id_type` is a sqla `hybrid_property`.  There's not really a reason why this should be a hybrid property though. I started using hybrid properties instead of the custom `class_property` but it seems that sqlalchemy does more than what's needed when hybrid properties are used.

The query when there's no `id` is not needed and I should remove it, in fact i just tried to remove it but my unit tests failed. I'll have to investigate this a bit more.

So, in HEAD, id_type is a classproperty now, but the query is still there. Can you check if this works for you?

Maybe using merge() is a better option too, I'll investigate that. (This project kinda grew "organically": I learned SQLAlchemy by writing this library, and I am certainly not a database expert. This means that a lot of things could be improved. I don't have the time for a complete rewrite atm and I'm happy that it's stable and convenient for the projects I use it for).

**Comment by thomaxxl** [comment]
I commited a new version with

```
     if "id" not in kwargs:
            return object.__new__(cls)
```

Can you check if this works for you?

The errors I got were because of my tests, not because of the change.

**Comment by agoe** [comment]
Hi Thomas,

might i bother you with another issue with Exception handling?

When I throw a validation error in the case of patch SAFRS always throws
genericError after catching Validation error.
This then is returned as HttpCode 500 to the client.

Somehow get is called up to 3? times after a patch
safrs_api.py
549 @wraps(fun) calles 3? times with get  once a  patch is called
       def method_wrapper(*args, **kwargs):

you can test it with the example
safrs/ex2_column_type.py at master · thomaxxl/safrs (github.com)
<https://github.com/thomaxxl/safrs/blob/master/examples/mini_examples/ex2_column_type.py>


Just try to patch a User via swagger and enter an email address without '@'
to trigger the validation error.

I can also create an issue if you prefer this.

Kind regards,

Achim

**Comment by agoe** [comment]
Hi Thomas,

dou you remember Vals Discussion where he would like to read related
Objects in a separate call for each page?

react-admin does this on the client side.

I need to implement  get many in the react-admin data provider:
The version I am currently using henvo/ra-jsonapi-client: JSON API data
provider for react-admin. (github.com)
<https://github.com/henvo/ra-jsonapi-client>
has implemented the get_many quite strange.

A proposal from react-admin is
getManyGET http://my.api.url/posts?filter={"id":[123,456,789]}

henvo/ra-jsonapi-client: JSON API data provider for react-admin.
(github.com) <https://github.com/henvo/ra-jsonapi-client>


Here is how this Data Provider maps react-admin calls to API calls:
React-admin - Data Providers (marmelab.com)
<https://marmelab.com/react-admin/DataProviders.html#writing-your-own-data-provider>


Method nameAPI call
getList GET http://my.api.url/posts?sort=["title","ASC"]&range=[0,
24]&filter={"title":"bar"}
getOne GET http://my.api.url/posts/123
getMany GET http://my.api.url/posts?filter={"id":[123,456,789]}
getManyReference GET http://my.api.url/posts?filter={"author_id":345}
create POST http://my.api.url/posts
update PUT http://my.api.url/posts/123
updateMany Multiple calls to PUT http://my.api.url/posts/123
delete DELETE http://my.api.url/posts/123
deleteMany


https://jsonapi.org/recommendations/#filtering
Jason Api.org is proposing:

Multiple filter values can be combined in a comma-separated list. For
example:

GET /comments?filter[post]=1,2 HTTP/1.1


I opted for
getManyGET http://my.api.url/posts?filter[id]=["123","456","789"]   to be
closer to the current Filter support
https://github.com/thomaxxl/safrs#filtering
and easier detection if multiple parameters are sent.


I created a test implementation for SAFRS .

jasonapi_filters.py line 42 before  cls._s_get_instance_by_id(val) i added
the check for [ ] in the query string

for attr_name, val in filters.items():
    if attr_name == "id":
        if val.startswith("[") and val.endswith("]"):
            ids = val[2:-2].split("\",\"") #  split string : "," for
["123","456","789"]

             return cls._s_get_many_by_ids(ids)

        return cls._s_get_instance_by_id(val)

in safrs base I added:

@classmethod
def _s_get_many_by_ids(cls, ids):
    """
    :param ids: jsonapi_id
    :return: query obj
    """
    # primary_keys = cls.id_type.get_pks(id) todo
    return cls._s_query.filter(cls.id.in_(ids))

It all works surprisingly well.
My react-admin enhanced  data-provider also runs well.
Needs some tests checking for data types and perhaps alternate id names.

Could you put this in to SAFRS as you were proposing some more filtering
capabilities for SAFRS?

Achim

**Comment by thomaxxl** [comment]
Regarding the multiple exceptions: this is caused because the ValidationError is only thrown when committing.
Before the commit() , safrs already does a get_instance() on an instance that's not valid. I don't understand how this works in sqla, but the solution seems to be to commit() immediately after the patch (in jsonapi/_patch_instance or base/_s_patch).

I've decided to add a commit after _s_patch, but I'm not sure how to handle this exception with bulk patch requests : 
- this would cause a pratial commit of the bulk patch request 
- For large patch requests this has a minor perf impact

I could commit in jsonapi.py, but I don't want to perform db calls in that file.
Anyway, I'll leave it like this for now. Can you check if this works?
I've also added an _s_upsert variable that is checked in `__new__` , can you see if that works for you?

**Comment by thomaxxl** [comment]
Regarding the getmany: can you push a PR? I'll merge it.
However, in these cases, I strongly prefer using HTTP2 request multiplexing: with multiplexing there's no need for seperate requests since you send all the different requests at once anyway. And I prefer to rely on HTTP rather than implementing something myself. That's one of the things I like about jsonapi in general btw, its semantics relies on HTTP instead of reimplementing similar functionality (for ex. status codes).

**Comment by agoe** [comment]
Thanks, Thomas,

validation errors in case of patch are now thrown as expected.

Achim

**Comment by thomaxxl** [comment]
I extended the filter with an `in` operator, so now you can use this to query multiple items:

`
filter={"name":"id", "op":"in", "val":[1,2]}
`
for ex:

`
http://thomaxxl.pythonanywhere.com/api/People/?filter={"name":"id", "op":"in", "val":[1,2]}
`
Does this work for you?

**Comment by thomaxxl** [comment]
these changes are in the 2.11 release
