### ISSUE TITLE
Doubts about SAFRS

### ISSUE THREAD

**Issue by kurianbenoy-aot** [thomaxxl/safrs#86]
-  Currently, I have a DB Model named Application Audit. Instead of the current SAFRS API approach of changing API endpoint as */application_audit*. I want to change it to the endpoint */application/history* even though the flask Model I want to use should be  Application_AUDIT itself. Can such an API endpoint name be shown in swagger documentation?

![image](https://user-images.githubusercontent.com/70306694/103068379-0349e800-45e3-11eb-8b05-e31a69a1e5c8.png)

- Will it is possible to include API_PREFIX when displaying swagger API documentation? So instead of /application_audit/ the swagger documentation will also show */api/application_audit*?

- Can an API endpoint which doesn't have any relation with SQLAlchemy and database also displayed with a description in swagger API documentation generated by safrs? Do you know any potential approach to include such API endpoints also into swagger documentation?

**Comment by thomaxxl** [comment]
You can override the `SAFRSBase._s_collection_name` to specify a different endpoint url, for example:
```python
class ApplicationAudit(Model):
    ....
    _s_collection_name = "application/history
```

You can provide a `custom_swagger` argument to `SAFRSApi`, which will be merged with the existing swagger, like in https://github.com/thomaxxl/safrs/blob/d48f082efe8726e50f84dc39d8f0cc49db5062c6/examples/demo_pythonanywhere_com.py#L267
Another option is to extract the swagger.json and edit it with the swagger editor to customize it, then host the swagger.json yourself.

**Comment by kurianbenoy-aot** [comment]
Thanks @thomaxxl. I am closing this issue, will reopen if I face any issues
