### ISSUE TITLE
swagger issue

### ISSUE THREAD

**Issue by simonwardjones** [thomaxxl/safrs#9]
Hi,

I noticed that the swagger json created has issues in the relations example.
e.g.
`$ref: '#/definitions/Book POST sample'`

This has the following error (to see this use http://editor.swagger.io/):
$ref values must be RFC3986-compliant percent-encoded URIs

I will have a look at fixing and then open a pull request.

Simon

**Comment by thomaxxl** [comment]
That issue started popping up after i modified get_operation_id to get more readable output iirc. swagger continued to work so it didn't really bother me but if you think you can fix it, that would be even better :)

**Comment by thomaxxl** [comment]
fixed in 1.0.17, thanks
